---
- name: Ejecutar proyecto de Azure Pipeline
  hosts: localhost
  tasks:
    - name: Clonar repositorio
      git:
        repo: <URL_del_repositorio>
        dest: /path/to/local/repository

    - name: Ejecutar script de compilación
      shell: |
        cd /path/to/local/repository
        ./build.sh
      register: build_output
      changed_when: build_output.stdout != ''

    - name: Desplegar en Azure Pipeline
      azure_devops_pipeline:
        org_url: https://dev.azure.com/<organization>
        project: <nombre_del_proyecto>
        pat: <token_de_acceso_personal>
        build_definition_id: <ID_de_definición_de_compilación>
        build_parameters:
          - name: repositoryPath
            value: /path/to/local/repository
          - name: buildOutput
            value: "{{ build_output.stdout }}"